# Use the official Node.js image as the base image
FROM node:18.17.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json from toodle-ui
COPY toodle-ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code from toodle-ui
COPY toodle-ui/ .

# Build the Next.js application
RUN npm run build  --verbose

# Expose the port the app runs on
EXPOSE 3000

# Set the command to run the app
CMD ["npm", "start"]