version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend-container
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8002:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend  # Path to the frontend directory containing the Dockerfile
    container_name: react-frontend
    ports:
      - "8003:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:1.19
    container_name: reverse-proxy
    ports:
      - "8004:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  db_data: